### ISSUE TITLE
Logo of institute in the navbar

### ISSUE THREAD

**Issue by AndreaCallia** [bk2dcradle/researcher#11]
Hi @ankitsultana and all,

does the theme provide a way to also put a logo of the institute in the navbar?

For example, by putting some specific item under `nav:`?

Many thanks for your work...

**Comment by ankitsultana** [comment]
At the moment, the answer is no. This could be thought of as an enhancement. I will look at this over the weekend.

**Comment by AndreaCallia** [comment]
In the mean time I have found a workaround made of two main changes.

In `_config.yml` I set the title as below.
```HTML
 title: "<img src=logo.jpg><br />Name Surname"
```

And, in order to avoid putting the HTML tags in the `<title>` tag, I use `strip_html` in liquid as shown below in the `default.html` file.
```HTML
<title>{% if page.title %}{{ page.title | strip_html }}{% else %}{{ site.title | strip_html }}{% endif %}</title>
```

In `_config.yml` you can also nest the `<img>` tag into a `<a>` tag if you want the logo to be a link to the institute (otherwise it would point to your `index.html` page as it is inside the `title` field). Again, thanks to `strip_html` the `<a>` tag will also be filtered out when generating the `<title>` tag.

I hope this helps.

PS @ankitsultana If you are too busy to make better improvements, you can modify your `default.html` file as I did, and you can add to your `README.md` the above instructions to add the logo in the `title:` field of `_config.yml`.

**Comment by ankitsultana** [comment]
I have added support for the institute logo at the top. Check out the README for more info.
