### ISSUE TITLE
Problems with line spacing in text

### ISSUE THREAD

**Issue by ZenanH** [bk2dcradle/researcher#17]
What should I do if I want the text to be more line spaced 😅?
![image](https://user-images.githubusercontent.com/19581645/93462136-69eea400-f918-11ea-9892-8042351f1def.png)

**Comment by ankitsultana** [comment]
Hey @ZenanH , seems like you have found a resolution but one way to do it is by adjusting `_style.scss` as you see fit: https://github.com/ankitsultana/researcher/blob/gh-pages/_sass/_style.scss

**Comment by ZenanH** [comment]
> Hey @ZenanH , seems like you have found a resolution but one way to do it is by adjusting `_style.scss` as you see fit: https://github.com/ankitsultana/researcher/blob/gh-pages/_sass/_style.scss

Thanks for the quick reply, I'll try it out.😎
