### ISSUE TITLE
Clicking the title doesn't redirect to the front page. 

### ISSUE THREAD

**Issue by songhee-kim** [bk2dcradle/researcher#20]
Hi Ankit, thanks for sharing your theme, first of all. I keep having this problem even when I minimally modify your theme. When I click the "title" of the webpage, it doesn't reload the front page but is stuck at whatever page it was at currently. For example, if I go to "contact" and then click the title again, it does not go back to the front page(i.e., index.md). Any ideas what causes this behavior? The site is [here](https://songhee-kim.github.io/).

**Comment by ankitsultana** [comment]
Hi @songhee-kim ,

Thanks for reporting this. Took a quick look and most likely the bug is here: https://github.com/ankitsultana/researcher/blob/gh-pages/_layouts/default.html#L62

I'll take a look at this over the weekend and raise a fix.

**Comment by ankitsultana** [comment]
Rolled out a fix. Can you try rebasing?

**Comment by sonhkim** [comment]
I did. it works now. Thanks!

**Comment by songhee-kim** [comment]
I just did and it works now. Thanks!
